--------------------------------------------------------
--  DDL for Table USER_AUTH
--------------------------------------------------------
CREATE TABLE USER_AUTH
(
    ID NUMBER(20, 0) NOT NULL
  , LOGIN VARCHAR2(256 BYTE) NOT NULL
  , PASSWORD VARCHAR2(256 BYTE) NOT NULL
  , USER_ID NUMBER(20, 0) NOT NULL
  , CONSTRAINT USER_AUTH_PK PRIMARY KEY
  (
    ID
  )
ENABLE
)
LOGGING
TABLESPACE "USERS"
PCTFREE 10
INITRANS 1
STORAGE
(
BUFFER_POOL DEFAULT
);

ALTER TABLE USER_AUTH
  ADD CONSTRAINT USER_AUTH_UK UNIQUE
  (
    LOGIN
    , USER_ID
  )
ENABLE;

ALTER TABLE USER_AUTH
  ADD CONSTRAINT USERS_FK FOREIGN KEY
  (
    USER_ID
  )
REFERENCES USERS
  (
    ID
  )
ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

CREATE TABLE USERS
(
    ID NUMBER(20, 0) NOT NULL
  , FIRST_NAME VARCHAR2(20 BYTE) NOT NULL
  , LAST_NAME VARCHAR2(30 BYTE) NOT NULL
  , EMAIL VARCHAR2(30 BYTE) NOT NULL
  , TEL_NUMBER VARCHAR2(15 BYTE) NOT NULL
  , GENDER VARCHAR2(6 BYTE) NOT NULL
  , BIRTHDAY VARCHAR2(20 BYTE) NOT NULL
  , INFO CLOB
  , CONSTRAINT USERS_PK PRIMARY KEY
  (
    ID
  )
ENABLE
)
LOGGING
TABLESPACE "USERS"
PCTFREE 10
INITRANS 1
STORAGE
(
BUFFER_POOL DEFAULT
)
LOB (INFO) STORE AS SYS_LOB0005646397C00008$$
(
ENABLE STORAGE IN ROW
CHUNK 8192
NOCACHE
LOGGING
);

ALTER TABLE USERS
  ADD CONSTRAINT USERS_UK UNIQUE
  (
    EMAIL
    , TEL_NUMBER
  )
ENABLE;



